# Written by https://github.com/DeterminateSystems/nix-installer.
# The contents below are based on options specified at installation time.

min-free = 32212254720   # 30 GB
max-free = 64424509440   # 60 GB
