# Written by https://github.com/DeterminateSystems/nix-installer.
# The contents below are based on options specified at installation time.

min-free = 53687091200   # 50 GB
max-free = 107374182400  # 100 GB
