# Change the prefix to Ctrl-a.
set -g prefix C-a
unbind C-b

# Pressing Ctrl-a twice will send Ctrl-a to other apps. This is allows for
# stuff like moving the cursor to the start of the line.
bind C-a send-prefix

# Set the delay between prefix and command.
set -s escape-time 1

set -g status-interval 1

# Reload config.
bind r source-file ~/.tmux.conf; display "Reloaded config"

# Use \ and - to split the window. Keep the same cwd when creating new panes.
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Create window with name prompt.
bind-key c command-prompt -p "window name:" "new-window; rename-window '%%'"

# Renumber windows when closing a window.
set -g renumber-windows on

# Cycle thru windows in a vim-like way.
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Navigate panes in a vim-like way.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes in a vim-like way.
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Enable mouse.
set -g mouse on

setw -g mode-keys vi

# Start window and pane numbering start at 1.
set -g base-index 1
setw -g pane-base-index 1

# Use 256 color mode.
set -g default-terminal "screen-256color"

# Status line colors.
set -g status-style fg=white,bg=black

# Status line content.
set -g status-left "#[fg=green]#S #[fg=default]| "
set -g status-left-length 20
set -g status-right '#{prefix_highlight}#{packet_loss}#[bg=color237]NET #{ping}#[fg=default]#{wifi_icon}#[fg=black]#{cpu_bg_color}CPU#{cpu_percentage}#[bg=black,fg=default] %m-%d #(TZ="America/Detroit" date +%%H:%%M:%%S) | UTC #(TZ="UTC" date +%%H:%%M)'
set -g status-right-length 80

# Center window list.
set -g status-justify left

# Highlight inactive window list items with activity.
set -g monitor-activity on

# Window list colors.
setw -g window-status-style fg=cyan,bg=black
setw -g window-status-current-style fg=black,bg=magenta

set -g pane-border-style fg=green
set -g pane-active-border-style fg=magenta

set -g @plugin 'ayzenquwe/tmux-ping'
set -g @plugin 'gmoe/tmux-wifi'

set -g @plugin 'jaclu/tmux-packet-loss'
set -g @packet-loss-level_disp 1
set -g @packet-loss-prefix "LOSS "
set -g @packet-loss-suffix " "

set -g @plugin 'thuanOwa/tmux-fzf-session-switch'

set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @cpu_percentage_format "%3.0f%%"

set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @prefix_highlight_output_suffix ''

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

